version: 2.0
jobs:
  build:
    docker:
      - image: apertium/base:release
    steps:
      - checkout

      - run: ./autogen.sh
      - run: make

      - run:
          name: Install apertium-quality
          command: |
            apt-get -y install python3 python3-setuptools
            git clone https://github.com/apertium/apertium-quality.git
            cd apertium-quality/mwtools/python3
            python3 ./setup.py install
            cd ../../
            ./autogen.sh && make && make install
            cd ../../../
