version: 2.0
jobs:
  build:
    docker:
      - image: apertium/base:release
    steps:
      - checkout

      - run: ./autogen.sh
      - run: make

      - run:
          name: Install apertium-quality
          command: |
            apt-get -y install python3 python3-setuptools python3-dev python3-yaml curl
            git clone https://github.com/apertium/apertium-quality.git
            cd apertium-quality/mwtools/python3
            python3 ./setup.py install
            cd ../../
            ./autogen.sh && make && make install
            cd ../../../

      - run:
          name: Install a little go program for fetching latest build artifacts
          command: |
            apt-get -y install golang
            export GOPATH=/tmp/gocode
            go get github.com/nbio/cart
            chmod u+x /tmp/gocode/bin/cart
            /tmp/gocode/bin/cart /tmp/cov.jam.txt

      - run:
          name: Measure coverage
          command: |
            curl https://raw.githubusercontent.com/taruen/apertiumpp/master/data4apertium/corpora/jam/tat.txt > /tmp/jam.tat.txt
            aq-covtest /tmp/jam.tat.txt tat.automorf.bin | tee | grep 'Coverage: ' | sed 's/Coverage: \(.*\)%/\1/g' > /tmp/cov.jam.txt
            echo "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"81\" height=\"20\"><linearGradient id=\"a\" x2=\"0\" y2=\"100%\"><stop offset=\"0\" stop-color=\"#bbb\" stop-opacity=\".1\"/><stop offset=\"1\" stop-opacity=\".1\"/></linearGradient><rect rx=\"3\" width=\"81\" height=\"20\" fill=\"#555\"/><rect rx=\"3\" x=\"37\" width=\"44\" height=\"20\" fill=\"#e05d44\"/><path fill=\"#e05d44\" d=\"M37 0h4v20h-4z\"/><rect rx=\"3\" width=\"81\" height=\"20\" fill=\"url(#a)\"/><g fill=\"#fff\" text-anchor=\"middle\" font-family=\"DejaVu Sans,Verdana,Geneva,sans-serif\" font-size=\"11\"><text x=\"19.5\" y=\"15\" fill=\"#010101\" fill-opacity=\".3\">jam</text><text x=\"19.5\" y=\"14\">jam</text><text x=\"58\" y=\"15\" fill=\"#010101\" fill-opacity=\".3\">$(cat /tmp/cov.jam.txt)%</text><text x=\"58\" y=\"14\">$(cat /tmp/cov.jam.txt)%</text></g></svg>" > /tmp/cov.jam.svg

            curl https://raw.githubusercontent.com/taruen/apertiumpp/master/data4apertium/corpora/udhr/udhr_tat.txt > /tmp/udhr.tat.txt
            aq-covtest /tmp/udhr.tat.txt tat.automorf.bin | tee | grep 'Coverage: ' | sed 's/Coverage: \(.*\)%/\1/g' > /tmp/cov.udhr.txt
            echo "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"81\" height=\"20\"><linearGradient id=\"a\" x2=\"0\" y2=\"100%\"><stop offset=\"0\" stop-color=\"#bbb\" stop-opacity=\".1\"/><stop offset=\"1\" stop-opacity=\".1\"/></linearGradient><rect rx=\"3\" width=\"81\" height=\"20\" fill=\"#555\"/><rect rx=\"3\" x=\"37\" width=\"44\" height=\"20\" fill=\"#e05d44\"/><path fill=\"#e05d44\" d=\"M37 0h4v20h-4z\"/><rect rx=\"3\" width=\"81\" height=\"20\" fill=\"url(#a)\"/><g fill=\"#fff\" text-anchor=\"middle\" font-family=\"DejaVu Sans,Verdana,Geneva,sans-serif\" font-size=\"11\"><text x=\"19.5\" y=\"15\" fill=\"#010101\" fill-opacity=\".3\">udhr</text><text x=\"19.5\" y=\"14\">udhr</text><text x=\"58\" y=\"15\" fill=\"#010101\" fill-opacity=\".3\">$(cat /tmp/cov.udhr.txt)%</text><text x=\"58\" y=\"14\">$(cat /tmp/cov.udhr.txt)%</text></g></svg>" > /tmp/cov.udhr.svg

      - store_artifacts:
          path: /tmp/cov.jam.txt

      - store_artifacts:
          path: /tmp/cov.jam.svg

      - store_artifacts:
          path: /tmp/cov.udhr.txt

      - store_artifacts:
          path: /tmp/cov.udhr.svg