version: 2.0
jobs:
  build:
    docker:
      - image: apertium/base:release
    steps:
      - checkout

      - run: ./autogen.sh
      - run: make

      - run:
          name: Install apertium-quality
          command: |
            apt-get -y install python3 python3-setuptools python3-dev python3-yaml curl
            git clone https://github.com/apertium/apertium-quality.git
            cd apertium-quality/mwtools/python3
            python3 ./setup.py install
            cd ../../
            ./autogen.sh && make && make install
            cd ../../../

      - run: curl https://raw.githubusercontent.com/taruen/apertiumpp/master/data4apertium/corpora/jam/tat.txt > /tmp/tat.txt
      - run: aq-covtest /tmp/tat.txt tat.automorf.bin | tee | grep "Coverage: " | sed 's/Coverage: \(.*\)%/\1/g' > /tmp/cov.jam.txt

      - store_artifacts:
          path: /tmp/cov.jam.txt